#!/bin/bash

xcode-select --install

if [ -z "$(type brew 2>/dev/null)" ]; then /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; fi

brew install bash bash-completion ansible awscli cfssl cmake coreutils figlet fswatch gcc git jq keychain macvim node openssl@1.1 python3 reattach-to-user-namespace ruby-build socat sphinx-doc terraform tmux unrar watch wget wireshark

ansible-playbook install-playbook.yml -i hosts
