# zmodload zsh/zprof
unalias run-help 2>/dev/null
autoload -Uz run-help
export ZSH="$HOME/.oh-my-zsh"
ZSH_DISABLE_COMPFIX=true

ZSH_THEME="yogeshlonkar"

CASE_SENSITIVE="true"

plugins=(
  autojump
  aws
  fzf
  git
  golang
  helm
  npm
  terraform
  vault
  vi-mode
  zsh-autosuggestions
  zsh-history-substring-search
  zsh-syntax-highlighting
  colored-man-pages
)

function __yrl__()
{
  local session=$(tmux display-message -p '#S')
  source $ZSH/oh-my-zsh.sh
  bindkey "\C-k" history-beginning-search-backward
  bindkey "\C-j" history-beginning-search-forward
  source $HOME/.yrl/environment
  if [[ -f $HOME/.yrl/secrets-$session ]]; then
    export $(envsubst < $HOME/.yrl/secrets-$session)
  fi
  source $HOME/.yrl/utils
  source $HOME/.yrl/aliases
  _CLI_ZSH_AUTOCOMPLETE_HACK=1
  source $HOME/zsh_autocomplete
  compdef _cli_zsh_autocomplete dazn
  [ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
}
if [[ -n "$TMUX" ]] || [[ $TERMINAL_EMULATOR == *"JetBrains"* ]] || [[ $TERM_PROGRAM == "vscode" ]]; then
  __yrl__
fi

setopt menu_complete
setopt list_rows_first
setopt no_share_history
unsetopt share_history

export PATH="/usr/local/sbin:$PATH"
# zprof
