# zmodload zsh/zprof
unalias run-help
autoload -Uz run-help
export ZSH="$HOME/.oh-my-zsh"
ZSH_DISABLE_COMPFIX=true

ZSH_THEME="yogeshlonkar"

CASE_SENSITIVE="true"

plugins=(
  autojump
  aws
  fzf
  git
  golang
  helm
  npm
  terraform
  vault
  vi-mode
  zsh-autosuggestions
  zsh-history-substring-search
  zsh-syntax-highlighting
  colored-man-pages
)

setopt menu_complete
setopt list_rows_first
unsetopt share_history

function __yrl__()
{
  local session=$(tmux display-message -p '#S')
  source $ZSH/oh-my-zsh.sh
  bindkey "\C-k" history-beginning-search-backward
  bindkey "\C-j" history-beginning-search-forward
  source $HOME/.yrl/environment
  if [[ -f $HOME/.yrl/secrets-$session ]]; then
    source $HOME/.yrl/secrets-$session
  fi
  source $HOME/.yrl/utils
  source $HOME/.yrl/aliases
  PROG=dazn
  _CLI_ZSH_AUTOCOMPLETE_HACK=1
  source $HOME/zsh_autocomplete
}
if [[ -n "$TMUX" ]]; then
  __yrl__
fi

[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
export PATH="/usr/local/sbin:$PATH"
# zprof
